# Generated by Django 3.2 on 2022-08-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_do', models.CharField(max_length=30)),
                ('task', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='lib',
        ),
    ]
