# Generated by Django 3.2 on 2022-08-03 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ceo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmp_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cmo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmo_name', models.CharField(max_length=30)),
                ('cmp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sant.ceo')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_man',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_manager', models.CharField(max_length=30)),
                ('ceo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sant.ceo')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_head', models.CharField(max_length=30)),
                ('man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sant.sales_man')),
            ],
        ),
        migrations.CreateModel(
            name='Sale_exe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_executive', models.CharField(max_length=30)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sant.sales_head')),
                ('man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sant.sales_man')),
            ],
        ),
        migrations.CreateModel(
            name='Pro_man',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('man_name', models.CharField(max_length=30)),
                ('cmo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sant.cmo')),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev', models.CharField(max_length=30)),
                ('cmo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sant.cmo')),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sant.pro_man')),
            ],
        ),
    ]
