# Generated by Django 3.2 on 2022-08-03 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ceo',
            old_name='cmp_name',
            new_name='ceo_name',
        ),
    ]
