# Generated by Django 3.2 on 2022-08-03 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sant', '0002_rename_cmp_name_ceo_ceo_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cmo',
            old_name='cmp',
            new_name='ceo',
        ),
    ]
