# Generated by Django 3.2 on 2022-08-03 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sant', '0003_rename_cmp_cmo_ceo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pro_man',
            new_name='Pro_manager',
        ),
        migrations.RenameField(
            model_name='pro_manager',
            old_name='cmo',
            new_name='cmo_name',
        ),
        migrations.RenameField(
            model_name='pro_manager',
            old_name='man_name',
            new_name='pro_manager',
        ),
    ]
