# Generated by Django 3.2 on 2022-08-03 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sant', '0004_auto_20220803_0629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developer',
            old_name='cmo',
            new_name='cmo_name',
        ),
        migrations.RenameField(
            model_name='developer',
            old_name='pro',
            new_name='product_manager',
        ),
    ]
