# Generated by Django 3.2 on 2022-08-03 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sant', '0005_auto_20220803_0630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale_exe',
            old_name='head',
            new_name='sales_head',
        ),
        migrations.RenameField(
            model_name='sale_exe',
            old_name='man',
            new_name='sales_man',
        ),
        migrations.RenameField(
            model_name='sales_head',
            old_name='man',
            new_name='sales_manager',
        ),
        migrations.RenameField(
            model_name='sales_man',
            old_name='ceo',
            new_name='ceo_name',
        ),
    ]
