# Generated by Django 3.2 on 2022-08-03 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sant', '0006_auto_20220803_0634'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sales_man',
            new_name='Sales_manager',
        ),
    ]
