# Generated by Django 3.2 on 2022-08-03 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sant', '0007_rename_sales_man_sales_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmo',
            name='ceo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sant.ceo'),
        ),
    ]
